# Generated by Django 6.0.1 on 2026-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('curriculum_vitae', models.FileField(upload_to='attachees/cvs/%Y/%m/%d/')),
                ('id_document', models.FileField(upload_to='attachees/id_docs/%Y/%m/%d/')),
                ('academic_transcript', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('school_letter', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='attachees/docs/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('consent_terms', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
