# Generated by Django 6.0.1 on 2026-02-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id_document', models.FileField(upload_to='documents/ids/')),
                ('intro_letter', models.FileField(upload_to='documents/letters/')),
                ('curriculum_vitae', models.FileField(upload_to='documents/cvs/')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('data_policy_consent', models.BooleanField(default=False)),
                ('terms_consent', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In-Progress', 'In-Progress'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes regarding the application.', null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_competence', models.IntegerField(default=0)),
                ('discipline', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='accounts.attachee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorship_quality', models.IntegerField(default=3)),
                ('environment_rating', models.IntegerField(default=3)),
                ('resource_availability', models.IntegerField(default=3)),
                ('student_comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='accounts.attachee')),
            ],
        ),
    ]
