# Generated by Django 6.0.1 on 2026-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachee',
            name='academic_transcript',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='consent_marketing',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='consent_terms',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='curriculum_vitae',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='expected_graduation_date',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='recommendation_letter',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='school_letter',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='attachee',
            name='national_id_number',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachee',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
