# Generated by Django 6.0.1 on 2026-01-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_attachee_academic_transcript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='nationality',
        ),
        migrations.AddField(
            model_name='attachee',
            name='curriculum_vitae',
            field=models.FileField(null=True, upload_to='docs/cvs/'),
        ),
        migrations.AddField(
            model_name='attachee',
            name='data_policy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachee',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attachee',
            name='id_document',
            field=models.FileField(null=True, upload_to='docs/ids/'),
        ),
        migrations.AddField(
            model_name='attachee',
            name='intro_letter',
            field=models.FileField(null=True, upload_to='docs/letters/'),
        ),
        migrations.AddField(
            model_name='attachee',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachee',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachee',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attachee',
            name='terms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
