# Generated by Django 6.0.1 on 2026-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_attachee_address_remove_attachee_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachee',
            name='signature_upload',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
