# Generated by Django 6.0.1 on 2026-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attachee_signature_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachee',
            name='data_policy_consent',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='marketing_consent',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='terms_consent',
        ),
        migrations.AddField(
            model_name='attachee',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='curriculum_vitae',
            field=models.FileField(default='', upload_to='documents/cvs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='id_document',
            field=models.FileField(default='', upload_to='documents/ids/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='intro_letter',
            field=models.FileField(default='', upload_to='documents/letters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='start_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachee',
            name='tracking_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
