# Generated by Django 6.0.1 on 2026-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_attachee_data_policy_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachee',
            name='data_policy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachee',
            name='institution',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachee',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachee',
            name='terms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
