# Generated by Django 6.0.1 on 2026-01-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorship_quality', models.IntegerField(default=3)),
                ('environment_rating', models.IntegerField(default=3)),
                ('resource_availability', models.IntegerField(default=3)),
                ('student_comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='accounts.attachee')),
            ],
        ),
    ]
