# Generated by Django 6.0.1 on 2026-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_attachee_end_date_alter_attachee_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachee',
            name='signature_data',
        ),
        migrations.RemoveField(
            model_name='attachee',
            name='signature_upload',
        ),
        migrations.AddField(
            model_name='attachee',
            name='signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/'),
        ),
    ]
