# Generated by Django 6.0.1 on 2026-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_attachee_signature_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachee',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachee',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
