# Generated by Django 6.0.1 on 2026-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_attachee_end_date_alter_attachee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
