# Generated by Django 6.0.1 on 2026-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_attachee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachee',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes regarding the application.', null=True),
        ),
    ]
