# Generated by Django 6.0.1 on 2026-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_attachee_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In-Progress', 'In-Progress'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
